### PR TITLE
Add usernames

### PR DESCRIPTION
**Pull request by sochotnicky**
This makes two changes - adds usernames and also tweaks for new topics (comment added/removed). 

Comment addition now actually triggers two identical messages in different topics. This is because single update can make other changes besides the comment change

### CODE REVIEW

**Comment by sochotnicky** [comment]
One side note - the coverage of some other modules (mostly CI with 70%) makes hitting the average coverage a bit annoying :-)

**Comment by sochotnicky** [comment]
Scratch that - will add agent while I am at it :-)

**Comment by sochotnicky** [comment]
OK. Done. Definitely done now.

**Comment by mikebonnet** [comment]
+1 This looks great, thanks Stano!

**Pull request merged**
